project_id = "qvmtzfvkhkhkhdpclzua"

[functions.admin-impersonate]
verify_jwt = true

[functions.admin-impersonate-end]
verify_jwt = false

[functions.twilio-call]
verify_jwt = true

[functions.twilio-webhook]
verify_jwt = false

[functions.twilio-setup]
verify_jwt = true

[functions.twilio-token]
verify_jwt = true

[functions.lead-webhook]
verify_jwt = false
